# Generated by Django 5.2.12 on 2026-03-11 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinica', 'Clínica'), ('Farmacia', 'Farmacia'), ('Centro Medico', 'Centro Médico'), ('Otro', 'Otro')], default='Hospital', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rol', models.CharField(choices=[('Médico', 'Médico'), ('Administrativo', 'Administrativo'), ('Enfermería', 'Enfermería'), ('Otro', 'Otro')], default='Médico', max_length=50)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('horario_preferido', models.CharField(blank=True, max_length=200, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('decisor_compra', models.BooleanField(default=False)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.institucion')),
            ],
        ),
    ]
