# Generated by Django 5.2.12 on 2026-03-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_institucion_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
