"""
Django settings for farmaview project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(!o%_+4au%5p7=nl))3%go^1n(5z3^!fk6%lut+a8ns)z@!r*&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Permitir que tu servidor funcione en ese dominio
ALLOWED_HOSTS = ['polet.pythonanywhere.com', 'localhost', '127.0.0.1']

# ¡SUPER IMPORTANTE PARA EL LOGIN! 
# Django necesita confiar en las respuestas que vienen desde Google hacia tu dominio
CSRF_TRUSTED_ORIGINS = ['https://polet.pythonanywhere.com']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Tus apps modulares
    'apps.usuarios.apps.UsuariosConfig',
    'apps.clientes.apps.ClientesConfig',
    'apps.visitas.apps.VisitasConfig',
    'apps.productos.apps.ProductosConfig',
    'apps.ventas.apps.VentasConfig',
    # Apps necesarias para allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # Los proveedores que queremos usar
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',

]

# allauth necesita un ID de sitio
SITE_ID = 1

MIDDLEWARE = [
    #allauth
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.visitas.context_processors.notificaciones_campana',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True
USE_L10N = True

USE_TZ = True
from django.utils.translation import gettext_lazy as _

# Idiomas disponibles
LANGUAGES = [
    ('es', _('Español')),
    ('en', _('English')),
]

# Carpeta donde se guardarán las traducciones
LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# AGREGAR ESTO 👇: Le dice a Django dónde encontrar tu carpeta root "static"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuracion de Usuario Personalizado
AUTH_USER_MODEL = 'usuarios.UsuarioPersonalizado'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = [
    # Para poder seguir iniciando sesión normal (correo/rut y contraseña)
    'django.contrib.auth.backends.ModelBackend',
    # Para la autenticación con Google y Microsoft
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Configuración de comportamiento
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
LOGIN_REDIRECT_URL = 'visitas:dashboard' # O la ruta a donde quieres que vayan al entrar

# Esto hace que al hacer clic en el botón, vaya directo a Google sin preguntar "Continuar"
SOCIALACCOUNT_LOGIN_ON_GET = True
# Conecta automáticamente la cuenta de Google con el usuario de Django si el email coincide
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True



#CIERRE SESION
LOGOUT_REDIRECT_URL = 'usuarios:login'