# Generated by Django 5.2.12 on 2026-03-19 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='jefe',
            field=models.ForeignKey(blank=True, help_text='Selecciona al Gerente o Jefe directo de este vendedor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to=settings.AUTH_USER_MODEL),
        ),
    ]
