# Generated by Django 5.2.12 on 2026-03-11 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de la visita')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('tipo_gestion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Gestión')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='clientes.contacto')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_programadas', to='clientes.institucion')),
                ('productos', models.ManyToManyField(blank=True, related_name='visitas', to='productos.producto')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
