# Generated by Django 5.2.12 on 2026-03-17 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_producto_stock'),
        ('visitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora Realizada')),
                ('notas', models.TextField(blank=True, null=True)),
                ('tipo_gestion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Gestión')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_visitas', to='clientes.contacto')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_visitas', to='clientes.institucion')),
                ('productos', models.ManyToManyField(blank=True, related_name='registros_visitas', to='productos.producto')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_visitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Visita',
                'verbose_name_plural': 'Registros de Visitas',
            },
        ),
    ]
