# Generated by Django 5.2.12 on 2026-03-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_registrovisita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
