# Generated by Django 5.2.12 on 2026-03-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_visita_razon_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovisita',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrovisita',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
