# Generated by Django 5.2.12 on 2026-03-26 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_institucion_razon_social'),
        ('ventas', '0003_pedido_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(help_text='Número del mes (1-12)')),
                ('anio', models.PositiveIntegerField(help_text='Año (Ej: 2026)')),
                ('monto_meta', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_mensuales', to='clientes.institucion')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta por Institución',
                'verbose_name_plural': 'Metas por Instituciones',
                'unique_together': {('institucion', 'representante', 'mes', 'anio')},
            },
        ),
    ]
