# Generated by Django 5.2.12 on 2026-03-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_metainstitucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='origen_excel',
            field=models.BooleanField(default=False),
        ),
    ]
